version: '3.7'
services:
  nginx:
    container_name: bp_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www/bp:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8100:80
      - 9100:81
    networks:
      - default
      - shared_bp
    depends_on:
      - php

  php:
    container_name: bp_php
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/runtime/.config/composer:/var/www/.composer
      - ~/.ssh:/root/.ssh
      - .:/var/www/bp:cached
#      - /var/www/bp/vendor       # exclude vendors       => MAC optimization - disable it on linux
      - symfony_cache:/tmp/bp:rw
    working_dir: /var/www/bp
    expose:
      - 9000
    networks:
      - default
      - shared_bp
    depends_on:
      - mysql
      - redis

  redis:
    container_name: bp_redis
    image: redis
    networks:
      - default

  mysql:
    container_name: bp_mysql
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: "%"
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/mariadb/collation.cnf:/etc/mysql/conf.d/collation.cnf
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    expose:
      - 3306
    ports:
      - 3326:3306
    networks:
      - default

  mongo:
    container_name: bp_db
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    env_file:
      - .env
    volumes:
      - ./docker/db/data:/data/db
    expose:
        - 27017
    ports:
      - 27117:27017
    networks:
      - default

  rabbitmq:
    container_name: bp_rabbitmq
    build: ./docker/rabbitmq
    ports:
      - 5682:5672
      - 15682:15672
    volumes:
      - ./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - default
      - shared_bp

volumes:
  symfony_cache:

networks:
  shared_bp:
    name: shared_bp
    external: true
